"""Single operation-to-emitter registry for the FreeCAD backend."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from ....topology import OperationNode

EMITTER_METHOD_BY_OP: Dict[str, str] = {
    "make_box_rsolid": "_emit_primitives",
    "make_cylinder_rsolid": "_emit_primitives",
    "make_cone_rsolid": "_emit_primitives",
    "make_sphere_rsolid": "_emit_primitives",
    "make_material_rmaterial": "_emit_products",
    "make_placement_rplacement": "_emit_products",
    "make_identity_placement_rplacement": "_emit_products",
    "make_part_rpart": "_emit_products",
    "make_assign_material_rpart": "_emit_products",
    "make_assembly_rassembly": "_emit_products",
    "make_add_component_rassembly": "_emit_products",
    "make_place_component_rassembly": "_emit_products",
    "make_face_connector_rconnector": "_emit_products",
    "make_edge_connector_rconnector": "_emit_products",
    "make_vertex_connector_rconnector": "_emit_products",
    "make_placement_connector_rconnector": "_emit_products",
    "make_add_connector_rpart": "_emit_products",
    "make_add_connector_rassembly": "_emit_products",
    "make_forward_connector_rassembly": "_emit_products",
    "make_connector_ref_rconnectorref": "_emit_products",
    "make_scalar_limit_rscalarlimit": "_emit_products",
    "make_ground_component_rassembly": "_emit_products",
    "make_unground_component_rassembly": "_emit_products",
    "make_fixed_constraint_rassembly": "_emit_products",
    "make_revolute_constraint_rassembly": "_emit_products",
    "make_prismatic_constraint_rassembly": "_emit_products",
    "make_gear_constraint_rassembly": "_emit_products",
    "make_belt_constraint_rassembly": "_emit_products",
    "make_rack_pinion_constraint_rassembly": "_emit_products",
    "make_solve_assembly_constraints_rassembly": "_emit_products",
    "make_compound_from_assembly_rcompound": "_emit_products",
    "make_select_rvertex": "_emit_selections",
    "make_select_redge": "_emit_selections",
    "make_select_rwire": "_emit_selections",
    "make_select_rface": "_emit_selections",
    "make_select_rshell": "_emit_selections",
    "make_select_rsolid": "_emit_selections",
    "apply_tag_rselection": "_emit_selections",
    "make_sketch_rsketch": "_emit_sketches",
    "add_point_rsketch": "_emit_sketches",
    "add_line_rsketch": "_emit_sketches",
    "add_circle_rsketch": "_emit_sketches",
    "add_arc_rsketch": "_emit_sketches",
    "add_bspline_rsketch": "_emit_sketches",
    "make_constrain_coincident_rsketch": "_emit_sketches",
    "make_constrain_point_on_rsketch": "_emit_sketches",
    "make_constrain_horizontal_rsketch": "_emit_sketches",
    "make_constrain_vertical_rsketch": "_emit_sketches",
    "make_constrain_parallel_rsketch": "_emit_sketches",
    "make_constrain_perpendicular_rsketch": "_emit_sketches",
    "make_constrain_collinear_rsketch": "_emit_sketches",
    "make_constrain_tangent_rsketch": "_emit_sketches",
    "make_constrain_concentric_rsketch": "_emit_sketches",
    "make_constrain_midpoint_rsketch": "_emit_sketches",
    "make_constrain_symmetric_rsketch": "_emit_sketches",
    "make_constrain_equal_length_rsketch": "_emit_sketches",
    "make_constrain_equal_radius_rsketch": "_emit_sketches",
    "make_constrain_distance_rsketch": "_emit_sketches",
    "make_constrain_distance_x_rsketch": "_emit_sketches",
    "make_constrain_distance_y_rsketch": "_emit_sketches",
    "make_constrain_length_rsketch": "_emit_sketches",
    "make_constrain_angle_rsketch": "_emit_sketches",
    "make_constrain_radius_rsketch": "_emit_sketches",
    "make_constrain_diameter_rsketch": "_emit_sketches",
    "make_constrain_fix_rsketch": "_emit_sketches",
    "make_wire_from_sketch_rwire": "_emit_sketches",
    "make_face_from_sketch_rface": "_emit_sketches",
    "make_line_redge": "_emit_geometry",
    "make_circle_redge": "_emit_geometry",
    "make_angle_arc_redge": "_emit_geometry",
    "make_three_point_arc_redge": "_emit_geometry",
    "make_spline_redge": "_emit_geometry",
    "make_interpolated_spline_redge": "_emit_geometry",
    "make_wire_from_edges_rwire": "_emit_geometry",
    "make_helix_redge": "_emit_geometry",
    "make_face_from_wire_rface": "_emit_geometry",
    "make_face_from_wires_rface": "_emit_geometry",
    "make_bezier_surface_rface": "_emit_surfaces",
    "fit_point_grid_rface": "_emit_surfaces",
    "make_ruled_surface_rface": "_emit_surfaces",
    "make_gordon_surface_rface": "_emit_surfaces",
    "make_surface_patch_rface": "_emit_surfaces",
    "make_loft_rshell": "_emit_surfaces",
    "sew_faces_rshell": "_emit_surfaces",
    "free_boundaries_rwirelist": "_emit_surfaces",
    "fill_holes_rshell": "_emit_surfaces",
    "make_extrude_rsolid": "_emit_features",
    "make_revolve_rsolid": "_emit_features",
    "make_loft_rsolid": "_emit_features",
    "make_sweep_rsolid": "_emit_features",
    "make_twisted_sweep_rsolid": "_emit_features",
    "make_cut_rsolid": "_emit_booleans",
    "make_union_rsolid": "_emit_booleans",
    "make_intersect_rsolid": "_emit_booleans",
    "make_2d_cut_rface": "_emit_booleans",
    "make_2d_union_rface": "_emit_booleans",
    "make_2d_intersect_rface": "_emit_booleans",
    "make_fillet_rsolid": "_emit_booleans",
    "make_chamfer_rsolid": "_emit_booleans",
    "make_shell_rsolid": "_emit_booleans",
    "make_mirror_rshape": "_emit_booleans",
    "make_translate_rshape": "_emit_transforms",
    "make_rotate_rshape": "_emit_transforms",
}


def emit_native_node(
    translator: Any,
    node: OperationNode,
    **kwargs: str,
) -> Optional[List[str]]:
    method_name = EMITTER_METHOD_BY_OP.get(node.op)
    if method_name is None:
        return None
    return getattr(translator, method_name)(node, **kwargs)


__all__ = ["EMITTER_METHOD_BY_OP", "emit_native_node"]
