#!/usr/bin/env python3
"""Generate Python and TypeScript types from the five Scene contract schemas."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from importlib.metadata import version
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "src/simplecadapi/scene/contracts/schemas"
PYTHON_OUTPUT = ROOT / "src/simplecadapi/scene/generated"
TYPESCRIPT_OUTPUT = ROOT / "scene-contract/src/generated"
PYTHON_GENERATOR_VERSION = "0.32.0"
TYPESCRIPT_GENERATOR_VERSION = "15.0.4"
SCHEMAS = (
    ("scene-1.0.schema.json", "scene", "SceneDocument"),
    ("entities-1.0.schema.json", "entities", "EntityDocument"),
    ("presentation-1.0.schema.json", "presentation", "PresentationDocument"),
    (
        "connector-binding-1.0.schema.json",
        "connector_binding",
        "ConnectorBindingDocument",
    ),
    (
        "normalized-product-1.schema.json",
        "normalized_product",
        "NormalizedProductDocument",
    ),
)


def _generator_schema(value: Any) -> Any:
    """Adapt 2020-12 vocabulary unsupported or weakened by the generators."""
    if isinstance(value, list):
        return [_generator_schema(item) for item in value]
    if not isinstance(value, dict):
        if isinstance(value, str) and value.startswith("#/$defs/"):
            return "#/definitions/" + value.removeprefix("#/$defs/")
        return value

    result: dict[str, Any] = {}
    for key, item in value.items():
        if key in {"const", "prefixItems"}:
            continue
        if key == "$defs":
            key = "definitions"
        if key == "$schema":
            item = "http://json-schema.org/draft-07/schema#"
        if key == "items" and "prefixItems" in value:
            continue
        result[key] = _generator_schema(item)

    if "const" in value:
        constant = _generator_schema(value["const"])
        if isinstance(constant, list):
            result.update(
                {
                    "type": "array",
                    "items": [{"enum": [item]} for item in constant],
                    "additionalItems": False,
                    "minItems": len(constant),
                    "maxItems": len(constant),
                }
            )
        else:
            result["enum"] = [constant]
    if "prefixItems" in value:
        result["items"] = _generator_schema(value["prefixItems"])
        exact_length = value.get("maxItems") == len(value["prefixItems"])
        result["additionalItems"] = (
            False if exact_length else _generator_schema(value.get("items", True))
        )
    return result


def _run(command: list[str]) -> None:
    subprocess.run(command, cwd=ROOT, check=True)


def _generate_python(schema_path: Path, output: Path, root_name: str) -> None:
    _run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(schema_path),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(output),
            "--output-model-type",
            "typing.TypedDict",
            "--target-python-version",
            "3.10",
            "--use-standard-collections",
            "--use-union-operator",
            "--enum-field-as-literal",
            "all",
            "--disable-timestamp",
            "--use-double-quotes",
            "--class-name",
            root_name,
        ]
    )


def _generate_typescript(schema_path: Path, output: Path) -> None:
    executable = ROOT / "scene-contract/node_modules/.bin/json2ts"
    if not executable.is_file():
        raise RuntimeError("run `npm install` in scene-contract before generating types")
    _run(
        [
            str(executable),
            "--input",
            str(schema_path),
            "--output",
            str(output),
            "--no-enableConstEnums",
            "--unreachableDefinitions",
            "--maxItems=-1",
        ]
    )


def _write_python_index(output: Path) -> None:
    imports = []
    names = []
    for _, module_name, root_name in SCHEMAS:
        imports.append(f"from .{module_name} import {root_name}\n")
        names.append(f'    "{root_name}",\n')
    output.joinpath("__init__.py").write_text(
        '"""Schema-generated Scene contract document types."""\n\n'
        + "".join(imports)
        + "\n__all__ = [\n"
        + "".join(names)
        + "]\n",
        encoding="utf-8",
    )


def _write_typescript_index(output: Path) -> None:
    exports = [
        f'export type {{ {root_name} }} from "./{module_name}.js";\n'
        for _, module_name, root_name in SCHEMAS
    ]
    output.joinpath("index.ts").write_text(
        "// Generated by tools/generate_scene_contract_types.py. Do not edit.\n\n"
        + "".join(exports),
        encoding="utf-8",
    )


def _generate(destination: Path, language: str) -> tuple[Path | None, Path | None]:
    schema_dir = destination / "schemas"
    python_dir = destination / "python"
    typescript_dir = destination / "typescript"
    schema_dir.mkdir(parents=True)
    if language in {"all", "python"}:
        python_dir.mkdir()
    if language in {"all", "typescript"}:
        typescript_dir.mkdir()

    for filename, module_name, root_name in SCHEMAS:
        schema = json.loads(SCHEMA_DIR.joinpath(filename).read_text(encoding="utf-8"))
        schema["title"] = root_name
        adapted_path = schema_dir / filename
        adapted_path.write_text(
            json.dumps(_generator_schema(schema), indent=2, ensure_ascii=True) + "\n",
            encoding="utf-8",
        )
        if language in {"all", "python"}:
            _generate_python(adapted_path, python_dir / f"{module_name}.py", root_name)
        if language in {"all", "typescript"}:
            _generate_typescript(adapted_path, typescript_dir / f"{module_name}.ts")

    if language in {"all", "python"}:
        _write_python_index(python_dir)
    if language in {"all", "typescript"}:
        _write_typescript_index(typescript_dir)
    return (
        python_dir if language in {"all", "python"} else None,
        typescript_dir if language in {"all", "typescript"} else None,
    )


def _files(directory: Path) -> dict[str, bytes]:
    if not directory.is_dir():
        return {}
    return {
        path.relative_to(directory).as_posix(): path.read_bytes()
        for path in sorted(directory.rglob("*"))
        if path.is_file() and path.suffix != ".pyc" and "__pycache__" not in path.parts
    }


def _sync(generated: Path, committed: Path, *, check: bool) -> bool:
    generated_files = _files(generated)
    committed_files = _files(committed)
    if generated_files == committed_files:
        return True
    if check:
        changed = sorted(generated_files.keys() ^ committed_files.keys())
        changed.extend(
            name
            for name in sorted(generated_files.keys() & committed_files.keys())
            if generated_files[name] != committed_files[name]
        )
        print(f"stale generated types in {committed.relative_to(ROOT)}:")
        for name in changed:
            print(f"  {name}")
        return False
    if committed.exists():
        shutil.rmtree(committed)
    shutil.copytree(generated, committed)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    parser.add_argument(
        "--language",
        choices=("all", "python", "typescript"),
        default="all",
    )
    args = parser.parse_args()

    if args.language in {"all", "python"}:
        installed = version("datamodel-code-generator")
        if installed != PYTHON_GENERATOR_VERSION:
            raise RuntimeError(
                f"expected datamodel-code-generator {PYTHON_GENERATOR_VERSION}, got {installed}"
            )
    if args.language in {"all", "typescript"}:
        package_path = (
            ROOT / "scene-contract/node_modules/json-schema-to-typescript/package.json"
        )
        if not package_path.is_file():
            raise RuntimeError("run `npm install` in scene-contract before generating types")
        installed = json.loads(package_path.read_text(encoding="utf-8"))["version"]
        if installed != TYPESCRIPT_GENERATOR_VERSION:
            raise RuntimeError(
                f"expected json-schema-to-typescript {TYPESCRIPT_GENERATOR_VERSION}, "
                f"got {installed}"
            )

    with tempfile.TemporaryDirectory(prefix="scene-contract-types-") as temporary:
        python_dir, typescript_dir = _generate(Path(temporary), args.language)
        current = True
        if python_dir is not None:
            current &= _sync(python_dir, PYTHON_OUTPUT, check=args.check)
        if typescript_dir is not None:
            current &= _sync(typescript_dir, TYPESCRIPT_OUTPUT, check=args.check)
    return 0 if current else 1


if __name__ == "__main__":
    raise SystemExit(main())
